### ISSUE TITLE
Layout.vue is not found

### ISSUE THREAD

**Issue by jwknz** [zlliang/vuepress-theme-jupiter#1] opened 2019-02-10 07:51 UTC
I get an error saying:

> Error: [vuepress] Failed to load custom theme "vuepress-theme-jupiter". File vuepress-theme-vuepress-theme-jupiter/Layout.vue does not exist.

But when I look in the node_modules folder I see that it is in the `layouts` folder

Is there a fix for this? or the result of using the alpha :-)

**Comment by zlliang** [comment] 2019-02-10 09:01
I cannot reproduce this bug, and the following is what I did:
1. Run `mkdir demo && cd demo && yarn add vuepress@next vuepress-theme-jupiter`,
2. create `README.md` in the `demo` directory and insert some texts,
3. apply `module.exports = { theme: 'jupiter' }` in `.vuepress/config.js`, and
4. run `yarn vuepress dev .`, and the site is alive.

Here is a checklist for you:
1. Are you sure you install `vuepress@next`, and
2. do you apply apply `module.exports = { theme: 'jupiter' }` in `.vuepress/config.js`?

If you still have problems, you can upload your environment settings and console logs in detail, so we can find the bug together! 😉

**Comment by jwknz** [comment] 2019-02-10 09:07
When following your steps it works as expected.

I did use npm instead of yarn and I added it into an existing project.

I’ll transfer my files in to this folder and see if something is causing the bug.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zlliang** [comment] 2019-02-11 00:21
Close this for now :)

**Closed** 2019-02-11 00:21 UTC
